name: CICD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deployment scripts on Synology Nas
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_NAME }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.USER_NAME}}
            password: ${{ secrets.USER_PASSWORD }}
            script: |
              whoami
              cd /volume1/homes/solduma
              source ./.bash_profile 
              cd /var/services/homes/solduma/my-page
              sudo su -c git checkout main
              sudo su -c git fetch --all
              sudo su -c git reset --hard origin/main
              sudo su -c pm2 kill
              cd frontend
              sudo su -c npm install
              sudo su -c npm run build
              sudo su -c pm2 start npm -- start
